version: '3'

services:
  nextjs:
    ports:
      - 3000:3000
    build: 
      context: "./"
      dockerfile: ./cyborn.dockerfile
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
      - .env.local
